### ISSUE TITLE
Upgrade to keycloak version 24.0.4 or higher

### ISSUE THREAD

**Issue by tania2** [ThoreKr/keycloak-last-login-event-listener#11]
In version 24.0.4, partial update to user attributes when updating users through the Admin User API is no longer supported ->  https://www.keycloak.org/docs/24.0.5/server_admin/#user-profile

![image](https://github.com/user-attachments/assets/19ff1219-3180-421c-8ea0-75a377d71b0d)

How it could be implemented?

**Comment by ThoreKr** [comment]
This extension does not rely on the admin api. Haven't tested it yet with a version past 24.0.2. But this changelog does not seem to affect the implementation. Have you tested it?

**Comment by levinuss** [comment]
I run keycloak 25.0.2 and the plugin continues to work as usual (the instance does not use attributes for another purpose than last-login)

**Comment by ThoreKr** [comment]
@levinuss Thank you for sharing your experience with a more recent version of kecloak.

@tania2 did you succeed with the update? 

I'd like to close this issue.

**Comment by tania2** [comment]
Having other issues to solve. I haven't yet done the Complete migration to
25.0.2. Thank you very much for your response :-)

Στις Τετ, 7 Αυγ 2024, 11:31 π.μ. ο χρήστης Thore ***@***.***>
έγραψε:

**Comment by ThoreKr** [comment]
Alright. Feel free to open a new issue, if you encounter any problems.
