### ISSUE TITLE
Extend the vent to any type of logins

### ISSUE THREAD

**Issue by semangard** [ThoreKr/keycloak-last-login-event-listener#3]
Hello,

I think you should consider other types of logins:
EventType.LOGIN, EventType.IDENTITY_PROVIDER_LOGIN, EventType.IDENTITY_PROVIDER_FIRST_LOGIN

Regards

**Comment by ThoreKr** [comment]
Aren't they subclasses of each other?

I haven't looked at it in too much detail, but login seemed to catch a fairly broad range of events when I tested it.

**Comment by semangard** [comment]
No they are different items of the public enum EventType

**Comment by ThoreKr** [comment]
Interesting. It seemed like some actions emitted multiple events.

Do you have a setup where you could test this? I can add then event types to the filter but currently don't have access to a setup which could verify it or time to set one up.

**Comment by semangard** [comment]
No I don't unfortunately
